ProjetoCardapio/Models/Prato.cs
using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ProjetoCardapio.Models
{
    public class Prato
    {
        [Key]
        public long Id { get; set; }

        [Required(ErrorMessage = "Por favor, preencha o campo {0}")]
        [MaxLength(64, ErrorMessage = "O tamanho máximo para {0} é de {1} caracteres.")]
        [Display(Name = "Nome do Prato")]
        public string NomeDoPrato { get; set; }

        [Required(ErrorMessage = "Por favor, preencha o campo {0}")]
        [Display(Name = "Categoria do Prato")]
        [ForeignKey("Categoria")]
        public long CategoriaId { get; set; }

        public Categoria? Categoria { get; set; }

        [Required(ErrorMessage = "Por favor, preencha o campo {0}")]
        [MaxLength(150, ErrorMessage = "O tamanho máximo para {0} é de {1} caracteres.")]
        [Display(Name = "Descrição do Prato")]
        public string Descricao { get; set; }

        [Required(ErrorMessage = "Por favor, preencha o campo {0}")]
        [Range(0.01, 999999.99, ErrorMessage = "O preço deve estar entre {1} e {2}")]
        [Column(TypeName = "decimal(18,2)")]
        public decimal Preco { get; set; }

        [ValidateNever]
        public ICollection<PedidoPrato> PedidosPratos { get; set; } = new List<PedidoPrato>();

        [StringLength(255)]
        public string? ImagemUrl { get; set; }
    }
}

ProjetoCardapio/Controllers/PratosController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Http;
using System.IO;
using Microsoft.AspNetCore.Hosting;
using ProjetoCardapio.Data;
using ProjetoCardapio.Models;

namespace ProjetoCardapio.Controllers
{
    public class PratosController : Controller
    {
        private readonly ProjetoCardapioContext _context;
        private readonly IWebHostEnvironment _webHostEnvironment;

        public PratosController(ProjetoCardapioContext context, IWebHostEnvironment webHostEnvironment)
        {
            _context = context;
            _webHostEnvironment = webHostEnvironment;
        }

        // GET: Pratos
        public async Task<IActionResult> Index()
        {
            return View(await _context.Prato.ToListAsync());
        }

        // GET: Pratos/Details/5
        public async Task<IActionResult> Details(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var prato = await _context.Prato
                .FirstOrDefaultAsync(m => m.Id == id);
            if (prato == null)
            {
                return NotFound();
            }

            return View(prato);
        }

        // GET: Pratos/Create
        public IActionResult Create()
        {
            ViewBag.Categorias = new SelectList(_context.Categoria, "Id", "NomeDaCategoria");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,NomeDoPrato,CategoriaId,Descricao,Preco,Imagem")] Prato prato, IFormFile imagem)
        {
            if (ModelState.IsValid)
            {
                
                if (imagem != null && imagem.Length > 0)
                {
                    
                    var caminhoImagem = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images", imagem.FileName);

                    
                    using (var stream = new FileStream(caminhoImagem, FileMode.Create))
                    {
                        await imagem.CopyToAsync(stream);
                    }

                    
                    prato.ImagemUrl = "/images/" + imagem.FileName;
                }

               
                _context.Add(prato);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }

            
            ViewBag.Categorias = new SelectList(_context.Categoria, "Id", "NomeDaCategoria", prato.CategoriaId);
            return View(prato);
        }

        // GET: Pratos/Edit/5
        public async Task<IActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var prato = await _context.Prato.FindAsync(id);
            if (prato == null)
            {
                return NotFound();
            }

            ViewBag.Categorias = new SelectList(_context.Categoria, "Id", "NomeDaCategoria", prato.CategoriaId);
            return View(prato);
        }

        // POST: Pratos/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(long id, [Bind("Id,NomeDoPrato,CategoriaId,Descricao,Preco,ImagemUrl")] Prato prato, IFormFile imagem)
        {
            if (id != prato.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    
                    if (imagem != null && imagem.Length > 0)
                    {
                        
                        var caminhoImagem = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "images", imagem.FileName);

                        // Salva a imagem no diretório
                        using (var stream = new FileStream(caminhoImagem, FileMode.Create))
                        {
                            await imagem.CopyToAsync(stream);
                        }

                        // Atualiza a URL da imagem
                        prato.ImagemUrl = "/images/" + imagem.FileName;
                    }

                    _context.Update(prato);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!PratoExists(prato.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }

            // Repassa a lista de categorias para a View
            ViewBag.Categorias = new SelectList(_context.Categoria, "Id", "NomeDaCategoria", prato.CategoriaId);
            return View(prato);
        }


        // GET: Pratos/Delete/5
        public async Task<IActionResult> Delete(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var prato = await _context.Prato
                .FirstOrDefaultAsync(m => m.Id == id);
            if (prato == null)
            {
                return NotFound();
            }

            return View(prato);
        }

        // POST: Pratos/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(long id)
        {
            var prato = await _context.Prato.FindAsync(id);
            if (prato != null)
            {
                _context.Prato.Remove(prato);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool PratoExists(long id)
        {
            return _context.Prato.Any(e => e.Id == id);
        }
    }
}

ProjetoCardapio/Views/Pratos/Create.cshtml
@model ProjetoCardapio.Models.Prato

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Prato</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" method="post" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="NomeDoPrato" class="control-label"></label>
                <input asp-for="NomeDoPrato" class="form-control" />
                <span asp-validation-for="NomeDoPrato" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CategoriaId" class="control-label"></label>
                <select asp-for="CategoriaId" class="form-control" asp-items="@(ViewBag.Categorias)">
                </select>
                <span asp-validation-for="CategoriaId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Descricao" class="control-label"></label>
                <input asp-for="Descricao" class="form-control" />
                <span asp-validation-for="Descricao" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Preco" class="control-label"></label>
                <input asp-for="Preco" class="form-control" />
                <span asp-validation-for="Preco" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label for="Imagem">Imagem</label>
                <input type="file" class="form-control" id="Imagem" name="Imagem" />
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ProjetoCardapio/Views/Pratos/Delete.cshtml
@model ProjetoCardapio.Models.Prato

@{
    ViewData["Title"] = "Excluir Prato";
}

<div class="container mt-5 d-flex justify-content-center">
    <div class="card">
        @if (!string.IsNullOrEmpty(Model.ImagemUrl))
        {
            <img src="@Model.ImagemUrl" class="card-img-top" alt="Imagem do prato" style="height: 150px; object-fit: cover;">
        }
        else
        {
            <img src="https://via.placeholder.com/150" class="card-img-top" alt="Imagem do prato" style="height: 150px; object-fit: cover;">
        }
        <div class="card-body text-center">
            <div class="alert alert-danger text-center" role="alert">
                Você está prestes a excluir este prato! Essa ação não pode ser desfeita.
            </div>
            <h5 class="card-title text-danger">Deseja realmente excluir este prato?</h5>
            <p><strong>Nome:</strong> @Model.NomeDoPrato</p>
            <p><strong>Preço:</strong> R$ @Model.Preco.ToString("F2")</p>
            <p><strong>Descrição:</strong> @Model.Descricao</p>
            <form asp-action="Delete" asp-route-id="@Model.Id" method="post">
                <button type="submit" class="btn btn-danger">Excluir</button>
                <a href="@Url.Action("Index", "Pratos")" class="btn btn-secondary">Cancelar</a>
            </form>
        </div>
    </div>
</div>

ProjetoCardapio/Views/Pratos/Details.cshtml
@model ProjetoCardapio.Models.Prato

@{
    ViewData["Title"] = "Detalhes do Prato";
}

<div class="container mt-5 d-flex justify-content-center">
    <div class="card" style="width: 18rem;">
        @if (!string.IsNullOrEmpty(Model.ImagemUrl))
        {
            <img src="@Model.ImagemUrl" class="card-img-top" alt="Imagem do prato" style="height: 200px; object-fit: cover;">
        }
        else
        {
            <img src="https://via.placeholder.com/150" class="card-img-top" alt="Imagem do prato" style="height: 200px; object-fit: cover;">
        }
        <div class="card-body text-center">
            <h5 class="card-title">@Model.NomeDoPrato</h5>
            <p class="card-text"><strong>Descrição:</strong> @Model.Descricao</p>
            <p class="card-text"><strong>Preço:</strong> R$ @Model.Preco.ToString("F2")</p>
            <a href="@Url.Action("Edit", "Pratos", new { id = Model.Id })" class="btn btn-primary">Editar</a>
            <a href="@Url.Action("Index", "Pratos")" class="btn btn-secondary">Voltar</a>
        </div>
    </div>
</div>

ProjetoCardapio/Views/Pratos/Edit.cshtml
@model ProjetoCardapio.Models.Prato

@{
    ViewData["Title"] = "Editar Prato";
}

<h3 class="display-6">Editando o prato: @Model.NomeDoPrato</h3>
<hr />

@using (Html.BeginForm("Edit", "Pratos", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-group">
        @Html.LabelFor(model => model.NomeDoPrato)
        @Html.TextBoxFor(model => model.NomeDoPrato, new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.NomeDoPrato, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.CategoriaId)
        @Html.DropDownListFor(model => model.CategoriaId, (SelectList)ViewBag.Categorias, "- Selecione -", new { @class = "form-control" })
        @Html.ValidationMessageFor(model => model.CategoriaId, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Descricao)
        @Html.TextAreaFor(model => model.Descricao, new { @class = "form-control", rows = 3 })
        @Html.ValidationMessageFor(model => model.Descricao, "", new { @class = "text-danger" })
    </div>

    <div class="form-group">
        @Html.LabelFor(model => model.Preco)
        @Html.TextBoxFor(model => model.Preco, new { @class = "form-control", type = "number", step = "0.01" })
        @Html.ValidationMessageFor(model => model.Preco, "", new { @class = "text-danger" })
    </div>


    <div class="form-group mt-3 text-center">
        Imagem do produto:
        <div class="mt-3">
            @if (!string.IsNullOrEmpty(Model.ImagemUrl))
            {
                <img src="@Model.ImagemUrl" alt="Imagem Atual" class="img-fluid mb-3" style="max-height: 150px; object-fit: cover;">
            }
            <br />
            <label for="imagem">Alterar Imagem</label>
            <input type="file" id="imagem" name="imagem" class="form-control" />
            @Html.ValidationMessageFor(model => model.ImagemUrl, "", new { @class = "text-danger" })
        </div>
        <button type="submit" class="btn btn-outline-dark mt-3">Salvar Alterações</button>
        <a href="@Url.Action("Index", "Pratos")" class="btn btn-outline-dark mt-3">Voltar para a lista de Pratos</a>
    </div>


    
}

ProjetoCardapio/Views/Pratos/Index.cshtml
@model IEnumerable<ProjetoCardapio.Models.Prato>

@{
    ViewData["Title"] = "Pratos";
}

<h1 class="display-6 text-center">Pratos</h1>

<hr />
<a href="@Url.Action("Create", "Pratos")" class="btn btn-outline-dark mb-3">Novo Prato</a>

<div class="container">
    <div class="row">
        @foreach (var prato in Model)
        {
            <div class="col-3 mb-4">
                
                <div class="card">
                    
                    <img class="card-img-top img-fluid" src="@prato.ImagemUrl" alt="Imagem do Prato" style="max-height: 150px; object-fit: cover;">
                    <div class="card-body">
                        <h5 class="card-title">@prato.NomeDoPrato</h5>
                        <p class="card-text">@prato.Descricao</p>
                        <p class="card-text"><strong>@prato.Preco.ToString("C")</strong></p>

                        <a href="@Url.Action("Details", "Pratos", new { id = prato.Id })" class="btn btn-outline-dark">Detalhes</a>

                        <a href="@Url.Action("Edit", "Pratos", new { id = prato.Id })" class="btn btn-outline-dark">Editar</a>

                        <a asp-action="Delete" asp-route-id="@prato.Id" class="btn btn-danger">Deletar</a>
                    </div>
                </div>
            </div>
        }
    </div>
</div>